# Generated by Django 4.1.7 on 2023-02-15 07:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgeVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_between', models.IntegerField(help_text='Enter an age between 0 and 100', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'verbose_name': 'Age Variant',
                'verbose_name_plural': 'Age Variants',
            },
        ),
        migrations.CreateModel(
            name='GenderVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
            ],
            options={
                'verbose_name': 'Gender Variant',
                'verbose_name_plural': 'Gender Variants',
            },
        ),
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation', models.CharField(help_text='Enter an occupation', max_length=100)),
            ],
            options={
                'verbose_name': 'Occupation',
                'verbose_name_plural': 'Occupations',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(help_text='Enter a place name', max_length=100)),
            ],
            options={
                'verbose_name': 'Place',
                'verbose_name_plural': 'Places',
            },
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='statics/people')),
                ('name', models.CharField(help_text='Enter a name', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('age', models.ForeignKey(blank=True, help_text='Select an age variant', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='people', to='home.agevariant')),
                ('gender_type', models.ForeignKey(blank=True, help_text='Select a gender variant', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='people', to='home.gendervariant')),
                ('occupation_type', models.ForeignKey(blank=True, help_text='Select an occupation', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='people', to='home.occupation')),
                ('places', models.ForeignKey(blank=True, help_text='Select a place', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='people', to='home.place')),
            ],
            options={
                'verbose_name': '',
            },
        ),
    ]
